// DNI 78008606N BIBILEISHVILI MAMALADZE, NIKOLOZ
#include "SNData.h"
#include "Agency.h"

#include <stdio.h>
#include <string>
#include <vector>
#include <iostream>
using namespace std;

int main()
{
   SNData::newSocialNetwork("TokTik",0.8,0.1);
   SNData::newSocialNetwork("Infagram",0.6,0.05);
   SNData::newSocialNetwork("YZ",0.5,0.2);
   SNData::newSocialNetwork("JungleBook",0.1,0.1);
   
   Agency pufosAmos("Los pufos amos",1000.0);
   
   pufosAmos.addInfluencer("Pijus Magnificus",0.25);
   pufosAmos.addInfluencer("Brian",0.15);

   pufosAmos.addInfluencer("Brian",0.55);   // ERR_DUPLICATED
   pufosAmos.addInfluencer("Loretta",1.05); // ERR_WRONG_COMMISSION

   pufosAmos.addInfluencer("Loretta",.75);

   cout << pufosAmos ;

   pufosAmos.addFollowers("Pijus Magnificus", "YZ", 500);
   pufosAmos.addFollowers("Bdian","MSNotExist",400);    // ERR_NOT_FOUND
   pufosAmos.addFollowers("Brian","MSNotExist",400);    // ERR_UNKNOWN_SN
   pufosAmos.addFollowers("Loretta","TokTik",1200);
   pufosAmos.addFollowers("Loretta","Infagram",1300);
   pufosAmos.addFollowers("Loretta","YZ",700);
   pufosAmos.addFollowers("Loretta","TokTik",300);
   pufosAmos.addFollowers("Brian","JungleBook",65);

   cout << pufosAmos ;

   // Event data
   cout << "---------- First event -----------" << endl;
   string snNames[] = { "TokTik", "JungleBook", "Infagram", "MSN", "YZ" };
   double evRat[]   = {  0.95,   0.05, 0.7, 0.003, 0.85 };
   vector<string> inm;
   inm.push_back("Loretta");
   inm.push_back("Pijus Ticus");  // ignore
   inm.push_back("Brian");
   inm.push_back("Pijus Magnificus");

   pufosAmos.newEvent(inm,5,snNames,evRat);
   cout << pufosAmos ;


   double moneyEvent = pufosAmos.collectCommissions();
   cout << "Money generated by the event: " << moneyEvent << endl
        << pufosAmos ;
   
   return 0;
}
